### ISSUE TITLE
Search term has to be lowercase

### ISSUE THREAD

**Issue by mdeguzis** [sketchbuch/vsc-workspace-sidebar#71]
I found that when I search for workspaces, I can't put in anything that is camel case or upper case, it has to be lowercase. The search should be case-insensitive.

Actual: CreateSIMSprint
Have to enter: createsimsprint

![image](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/3931917/ccf2ff06-2d10-4629-9752-05254f0e625e)
![image](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/3931917/8009175e-9f18-4a74-8dee-25b789e80a00)

I took a look at the scripts in package.json, but `yarn test` doesn't seem to run tests.

**Comment by sketchbuch** [comment]
Hi, sorry for not replying earlier. I had the wrong watch settings for this repo and never get notified about new issues. I shall address this in the next release.

To run tests you need to uses the test command via the debug panel. I shall update the documentation - this is how the extensions work and not due to my setup.

**Comment by sketchbuch** [comment]
Done. Will be in the next release

![Screenshot from 2023-08-23 16-39-52](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/16445037/1605c993-33a3-47b2-8b92-991bd15ade68)

**Comment by sketchbuch** [comment]
In [v1.5.0](https://marketplace.visualstudio.com/items?itemName=sketchbuch.vsc-workspace-sidebar)
