### ISSUE TITLE
File Icons Not Rendering - Windows

### ISSUE THREAD

**Issue by hl2guide** [sketchbuch/vsc-workspace-sidebar#89]
Might be a bug in v1.7:

![a](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/17044982/08ecac96-f85a-48e6-ba5f-dbcccbc33250)

**Comment by hl2guide** [comment]
> What OS are you using? Have you changed where extensions for vscode are installed?

Window 10 Pro, no I haven't.

**Comment by hl2guide** [comment]
> Can you tell me what theme this was and show me what config you have for mapping icons. Thanks

ah okay, my File Icon theme is set to Seti (vs-seti). Do you have an icon set you recommend for this?

**Comment by sketchbuch** [comment]
Yeah, tested lots and I see the seti icons in 1.7.0 Mac and Linux. I will check windows again.

Can you open the developer tools and see if you can see any network errors or console errors when you switch to the sidebar

Seti Icons in v1.7.0 and developer tools showing loading resources
<img width="1376" alt="Screenshot 2023-10-11 at 11 15 41" src="https://github.com/sketchbuch/vsc-workspace-sidebar/assets/16445037/2d1ea08f-62cd-410a-9862-8595a8c66835">

**Comment by sketchbuch** [comment]
Seti use an icon font (codicons) rather than individual images. You can see it loading in the network tab in my previous comment.

**Comment by hl2guide** [comment]
I think the seti icon config was left over after the extension was removed in the past.

My testing:

- https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons

![file-icons](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/17044982/69c7d3d8-3dec-4ce5-9e7b-55f440e5794f)


- https://marketplace.visualstudio.com/items?itemName=emmanuelbeziat.vscode-great-icons

![great icons](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/17044982/7e65d235-d6b2-457e-848c-f30220b0c427)

I check for any network errors now.

**Comment by hl2guide** [comment]
![Uploading network error.png…]()

**Comment by sketchbuch** [comment]
I think this must be a windows issue. I will check later in a VM. Both those icons work on mac and Linux. Sorry about this.

**Comment by sketchbuch** [comment]
I believe I have fixed the issue. It was due to the way I was setting the base path to the extension folder with the icons. It worked on linux/mac but not on windows.

Can you unistall the version you have, go here: https://github.com/sketchbuch/vsc-workspace-sidebar/wiki

And download "vsc-workspace-sidebar-1.7.1.zip".

Extract that archive and you will find a vsix file inside which you can install in the extension manager.

![Install VSIX](https://github.com/sketchbuch/vsc-workspace-sidebar/assets/16445037/10d9029c-844b-4aa3-b843-6389b60a9ab6)

If this version shows you icons (which it did for me in my Windows VM), I shall release a new version with the fix.

**Comment by sbungert-mms** [comment]
In v1.7.1

**Comment by sketchbuch** [comment]
In v1.7.1
