### ISSUE TITLE
Multi-Profile Support

### ISSUE THREAD

**Issue by LittleLion2022** [sketchbuch/vsc-workspace-sidebar#95]
Now the setting applies to all profiles, but multi-profile will be better.

For Windows, `workspace.folder` is `D:\XXXX\workspaces`, that's my default profile.  

For a remote server, `workspace.folder` should be `/home/user/workspaces` rather than `D:\XXXX\workspaces`
#11 .

But now only the default profile takes effect.

https://code.visualstudio.com/docs/editor/profiles

**Comment by sketchbuch** [comment]
Will be in v2.0.0

Config for rootFolders is now machine scoped, rather than application. Remote settings can be used to override rootFolders. 

This change in scope means that folders are no longer synced since each machine needs to set their own folders.

Wasn't possible to connect settings to profile. The [API does not provide a way to get information about the profile in use](https://github.com/microsoft/vscode/issues/177463), but I was able to have different settings when I ssh into a VM that allow changing the folders.
